name       : ruby-rb-fsevent
version    : 0.10.4
release    : 5
source     :
    - https://rubygems.org/downloads/rb-fsevent-0.10.4.gem : 0741522cac72db1fc15250453b557a57f896a60ede7ba64f73e281688fd42bcd
license    : MIT
component  : programming.ruby
summary    : RubyGem - rb-fsevent
description: |
    FSEvents API with Signals catching (without RubyCocoa).
builddeps  :
    - pkgconfig(ruby-3.0)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
