name       : ruby-rb-fsevent
version    : 0.10.3
release    : 3
source     :
    - https://rubygems.org/downloads/rb-fsevent-0.10.3.gem : a8f78186feb55bb98579b5e0f8dd925ececfde1b5c2496e5e932997ff999a1d2
license    : MIT
component  : programming.ruby
summary    : RubyGem - rb-fsevent
description: |
    FSEvents API with Signals catching (without RubyCocoa).
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
